server:
  port: 9296
  
  
spring:  application:    name: CONFIG-SERVER
  cloud:
    gateway:
      routes:
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - Path=/departments/**